name: Update all buckets
on:
  schedule:
    - cron: 0 0 * * 3
jobs:
  update:
    name: Execute update scripts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute update script
        run: |
            for updater in misc/update-*.py; do
                python $updater
            done
      - name: "Check if there is any change"
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: ".commit_messages"
      - name: Commit changes (if there is any)
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git config --global user.name actions-user
          git config --global user.email "actions@github.com"
          git commit -a -F .commit_messages
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
